language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

before_deploy:
  - echo $GITHUB_TOKEN > .env
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s ghprofile --auth $NETLIFY_TOKEN -p --dir ./build
  skip_cleanup: true
  on:
    branch: master
